SELECT
    c.NOME || ' ' || c.SOBRENOME AS NOME_COMPLETO_CLIENTE,
    c.DOCUMENTO,
    COUNT(DISTINCT ccont.TB_CONTATO3_ID_CONTATO) AS TOTAL_CONTATOS,
    COUNT(DISTINCT cend.TB_ENDERECO3_ID_ENDERECO) AS TOTAL_ENDERECOS,
    SUM(CASE WHEN ct.TIPO_CONTATO = 'Principal' THEN 1 ELSE 0 END) AS CONTATOS_PRINCIPAIS
FROM
    GLOBAL.TB_CLIENTE3 c
JOIN
    GLOBAL.TB_CLIENTECONTATO3 ccont ON c.ID_CLIENTE = ccont.TB_CLIENTE3_ID_CLIENTE
JOIN
    GLOBAL.TB_CONTATO3 ct ON ccont.TB_CONTATO3_ID_CONTATO = ct.ID_CONTATO
JOIN
    GLOBAL.TB_CLIENTEENDERECO3 cend ON c.ID_CLIENTE = cend.TB_CLIENTE3_ID_CLIENTE
GROUP BY
    c.ID_CLIENTE, c.NOME, c.SOBRENOME, c.DOCUMENTO
HAVING
    COUNT(DISTINCT ccont.TB_CONTATO3_ID_CONTATO) >= 1 AND
    COUNT(DISTINCT cend.TB_ENDERECO3_ID_ENDERECO) >= 1
ORDER BY
    TOTAL_ENDERECOS DESC, NOME_COMPLETO_CLIENTE ASC;